version: '3.8'
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

  owasp-zap:
    image: owasp/zap2docker-stable
    container_name: owasp-zap
    command: zap-baseline.py -t http://app:8080 -r zap_report.html

  app:
    build: ./src
    container_name: devsecops-app
    ports:
      - "8080:8080"
