name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    environment: Reto_DevSecOps 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check AWS identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
            aws sts get-caller-identity
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g serverless@3
          serverless plugin install -n serverless-python-requirements
          
      - name: Run SAST with Bandit
        continue-on-error: true
        run: |
          pip install bandit
          bandit -r . -x node_modules,venv --skip B108

      - name: SCA with OWASP Dependency-Check (console)
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        with:
          project: 'My Project (console)'
          path: '.'
          format: 'CONSOLE'
      
      - name: SCA with OWASP Dependency-Check (html)
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        with:
          project: 'My Project (html)'
          path: '.'
          format: 'HTML'
          out: '/github/workspace/reports'
      
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: dependency-check-report
          path: /github/workspace/reports/dependency-check-report.html
        
      
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          serverless deploy

      - name: Send findings to AWS Security Hub
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws securityhub batch-import-findings --findings file://findings.json
