name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g serverless
          serverless plugin install -n serverless-python-requirements

      - name: Run SAST with Bandit
        run: |
          pip install bandit
          bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}"

      - name: Run SCA with OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ runner.tool_cache }}/jdk/11.0.19/x64
        with:
          project: 'My Project'
          path: '.'
          format: 'HTML'
      
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          serverless deploy

      - name: Send findings to AWS Security Hub
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          # EJEMPLO SENCILLO: findings.json debe existir y estar formateado correctamente
          aws securityhub batch-import-findings --findings file://findings.json
