name: CI/CD DevSecOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Build de imágenes con Docker Compose
        run: docker compose build

      - name: Levantar servicios con Docker Compose
        run: docker compose up -d

      - name: Esperar a que la aplicación esté lista
        run: sleep 30

      - name: Ejecutar pruebas de la aplicación
        run: |
          curl -f http://localhost:8080 || (echo "La aplicación no respondió" && exit 1)

      - name: Análisis con SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Ejecutar OWASP Dependency-Check vía Docker
        run: |
          docker run --rm -v $(pwd):/src owasp/dependency-check:latest \
          --project "DevSecOps Challenge" --scan /src --format "HTML" --out /src/dependency-check-report.html

      - name: Ejecutar escaneo DAST con OWASP ZAP
        run: |
          docker run --rm -v $(pwd):/zap/wrk owasp/zap2docker-stable \
          zap-baseline.py -t http://localhost:8080 -r zap_report.html

      - name: Detener servicios
        run: docker compose down
